import type { InventoryItem, EquippedItems } from "@/stores/inventory_items";

export const mockAroundItems: InventoryItem[] = [
    {
        itemId: 'firstWeapon',
        name: 'AK-47',
        icon: './items/akm.png',
        health: 39,
        itsize: 1,
        slotable: 3,
        stackable: 1,
        weight: 12,
        dtext1: 'AK-47 - это автоматическая винтовка, разработанная в 1947 году Михаилом Калашниковым в СССР.',
        dtext2: 'скорострельность - 600 выстрелов в минуту',
        dtext3: 'магазин на 30 патронов',
        dtext4: 'дальность стрельбы - 300 метров'
    },
    {
        itemId: 'clothesVest',
        name: 'Тактический жилет',
        icon: './items/tactvest.png',
        health: 75,
        itsize: 1,
        slotable: 3,
        stackable: 2,
        weight: 7,
        dtext1: 'Тактический жилет - это бронежилет, который защищает тело от пуль и осколков.',
        dtext2: 'прочность - 75%',
        dtext3: 'защита от пуль - 50%',
        dtext4: 'защита от осколков - 30%'
    },
    {
        itemId: 'medicineKit',
        name: 'Аптечка',
        icon: './items/medic.png',
        health: 100,
        itsize: 1,
        needsize: 5,
        slotable: 1,
        stackable: 5,
        weight: 1,
        dtext1: 'Аптечка - это медицинский инструмент, который используется для лечения ран и травм.',
        dtext2: 'восстанавливает 50% здоровья',
    }
]
export const mockInventoryItems: InventoryItem[] = [
    {
        itemId: 'firstWeapon',
        name: 'AK-47',
        icon: './items/akm.png',
        health: 39,
        itsize: 1,
        slotable: 3,
        stackable: 1,
        weight: 12,
        dtext1: 'AK-47 - это автоматическая винтовка, разработанная в 1947 году Михаилом Калашниковым в СССР.',
        dtext2: 'скорострельность - 600 выстрелов в минуту',
        dtext3: 'магазин на 30 патронов',
        dtext4: 'дальность стрельбы - 300 метров'
    },
    {
        itemId: 'clothesVest',
        name: 'Тактический жилет',
        icon: './items/tactvest.png',
        health: 75,
        itsize: 1,
        slotable: 3,
        stackable: 2,
        weight: 7,
        dtext1: 'Тактический жилет - это бронежилет, который защищает тело от пуль и осколков.',
        dtext2: 'прочность - 75%',
        dtext3: 'защита от пуль - 50%',
        dtext4: 'защита от осколков - 30%'
    },
    {
        itemId: 'medicineKit',
        name: 'Аптечка',
        icon: './items/medic.png',
        health: 100,
        itsize: 1,
        needsize: 5,
        slotable: 1,
        stackable: 5,
        weight: 1,
        dtext1: 'Аптечка - это медицинский инструмент, который используется для лечения ран и травм.',
        dtext2: 'восстанавливает 50% здоровья',
    },
    {
        itemId: 'firstWeapon',
        name: 'AK-47',
        icon: './items/akm.png',
        health: 39,
        itsize: 1,
        slotable: 3,
        stackable: 1,
        weight: 12,
        dtext1: 'AK-47 - это автоматическая винтовка, разработанная в 1947 году Михаилом Калашниковым в СССР.',
        dtext2: 'скорострельность - 600 выстрелов в минуту',
        dtext3: 'магазин на 30 патронов',
        dtext4: 'дальность стрельбы - 300 метров'
    },
    {
        itemId: 'clothesVest',
        name: 'Тактический жилет',
        icon: './items/tactvest.png',
        health: 75,
        itsize: 1,
        slotable: 3,
        stackable: 2,
        weight: 7,
        dtext1: 'Тактический жилет - это бронежилет, который защищает тело от пуль и осколков.',
        dtext2: 'прочность - 75%',
        dtext3: 'защита от пуль - 50%',
        dtext4: 'защита от осколков - 30%'
    },
    {
        itemId: 'medicineKit',
        name: 'Аптечка',
        icon: './items/medic.png',
        health: 100,
        itsize: 1,
        needsize: 5,
        slotable: 1,
        stackable: 5,
        weight: 1,
        dtext1: 'Аптечка - это медицинский инструмент, который используется для лечения ран и травм.',
        dtext2: 'восстанавливает 50% здоровья',
    },
    {
        itemId: 'firstWeapon',
        name: 'AK-47',
        icon: './items/akm.png',
        health: 90,
        itsize: 1,
        slotable: 3,
        stackable: 1,
        weight: 12,
        dtext1: 'AK-47 - это автоматическая винтовка, разработанная в 1947 году Михаилом Калашниковым в СССР.',
        dtext2: 'скорострельность - 600 выстрелов в минуту',
        dtext3: 'магазин на 30 патронов',
        dtext4: 'дальность стрельбы - 300 метров'
    },
    {
        itemId: 'firstWeapon',
        name: 'AWP',
        icon: './items/awp.png',
        health: 69,
        itsize: 1,
        slotable: 3,
        stackable: 1,
        weight: 14,
        dtext1: 'AWP - снайперская винтовка Британского производства, разработанная в компании Accuracy International',
        dtext2: 'скорострельность - 10 выстрелов в минуту',
        dtext3: 'магазин на 5 | 10 патронов',
        dtext4: 'альность стрельбы - 1500 метров'
    },
    {
        itemId: 'weaponMags9mm',
        name: '9mm боеприпас',
        icon: './items/9mm.png',
        health: 100,
        itsize: 1,
        slotable: 1,
        stackable: 3,
        weight: 2,
        dtext1: 'Пистолетный унитарный патрон с бесфланцевой гильзой цилиндрической формы с небольшой конусностью',
        dtext2: 'Категория: боеприпас.',
        dtext3: 'Начальная скорость пули, 350…380м/с',
        dtext4: 'Энергия пули, 480-617Дж'
    },
    {
        itemId: 'clothesVest',
        name: 'Тактический жилет',
        icon: './items/tactvest.png',
        health: 75,
        itsize: 1,
        slotable: 3,
        stackable: 2,
        weight: 7,
        dtext1: 'Тактический жилет - это бронежилет, который защищает тело от пуль и осколков.',
        dtext2: 'прочность - 75%',
        dtext3: 'защита от пуль - 50%',
        dtext4: 'защита от осколков - 30%'
    },
    {
        itemId: 'medicineKit',
        name: 'Аптечка',
        icon: './items/medic.png',
        health: 100,
        itsize: 1,
        needsize: 5,
        slotable: 1,
        stackable: 5,
        weight: 1,
        dtext1: 'Аптечка - это медицинский инструмент, который используется для лечения ран и травм.',
        dtext2: 'восстанавливает 50% здоровья',
    },
    {
        itemId: 'foodCola',
        name: 'Банка колы',
        icon: './items/cola.png',
        health: 100,
        itsize: 1,
        needsize: 3,
        slotable: 1,
        stackable: 3,
        weight: 1,
        dtext1: 'Категория: еда. Сладкий газированный напиток объемом 0.5л',
        dtext2: 'Восстанавливает немного выносливости'
    },
    {
        itemId: 'foodCola',
        name: 'Банка колы',
        icon: './items/cola.png',
        health: 100,
        itsize: 1,
        needsize: 3,
        slotable: 1,
        stackable: 3,
        weight: 1,
        dtext1: 'Категория: еда. Сладкий газированный напиток объемом 0.5л',
        dtext2: 'Восстанавливает немного выносливости'
    },
    {
        itemId: 'foodCola',
        name: 'Банка колы',
        icon: './items/cola.png',
        health: 100,
        itsize: 1,
        needsize: 3,
        slotable: 1,
        stackable: 3,
        weight: 1,
        dtext1: 'Категория: еда. Сладкий газированный напиток объемом 0.5л',
        dtext2: 'Восстанавливает немного выносливости'
    }
]

export const mockEquippedItems: EquippedItems = {
    weapons: [
        {
            itemId: 'firstWeapon',
            name: 'AK-47',
            icon: './items/akm.png',
            health: 69,
            itsize: 1,
            slotable: 3,
            stackable: 1,
            weight: 12,
            dtext1: 'AK-47 - это автоматическая винтовка, разработанная в 1947 году Михаилом Калашниковым в СССР.',
            dtext2: 'скорострельность - 600 выстрелов в минуту',
            dtext3: 'магазин на 30 патронов',
            dtext4: 'дальность стрельбы - 300 метров'
        }
    ],
    vest: {
        itemId: 'clothesVest',
        name: 'Тактический жилет',
        icon: './items/tactvest.png',
        health: 75,
        itsize: 1,
        slotable: 3,
        stackable: 2,
        weight: 7,
        dtext1: 'Тактический жилет - это бронежилет, который защищает тело от пуль и осколков.',
        dtext2: 'прочность - 75%',
        dtext3: 'защита от пуль - 50%',
        dtext4: 'защита от осколков - 30%'
    },
    medicine: [
        {
            itemId: 'medicineKit',
            name: 'Аптечка',
            icon: './items/medic.png',
            health: 100,
            itsize: 1,
            needsize: 5,
            slotable: 1,
            stackable: 5,
            weight: 1,
            dtext1: 'Аптечка - это медицинский инструмент, который используется для лечения ран и травм.',
            dtext2: 'восстанавливает 50% здоровья',
        },
    ],
    backpack: {
        itemId: 'clothesBackpackKoyote',
        name: 'Рюкзак-Койот',
        icon: './items/backpack.png',
        health: 100,
        itsize: 1,
        needsize: 1,
        slotable: 1,
        stackable: 1,
        weight: 15,
        dtext1: 'Рюкзак Койот',
        dtext2: 'вместимость - 40 слотов',
        dtext3: 'Тактический рюкзак средней вместимости',
    }
}